### ISSUE TITLE
phylophlan_write_default_configs.sh doesn't write threads parameter for RAxML

### ISSUE THREAD

**Issue by ipetrushin** [biobakery/phylophlan#10]
Dear Phylophlan Team!

Thanks for 3.0 release and all efforts to make it work better. 
phylophlan_write_default_configs.sh not adding threads setting into configs. Spend several hours to wait for the tree to be processed while noticed RAxML working single thread.

Default config section looks as follows:
```
[tree2]
program_name = /usr/bin/raxmlHPC-PTHREADS-SSE3
params = -p 1989 -m GTRCAT
database = -t
input = -s
output_path = -w
output = -n
version = -v
command_line = #program_name# #params# #threads# #database# #output_path# #input# #output#
```

need to add
`threads = -T`

**Comment by fasnicar** [comment]
Dear Ivan,

Thanks for using PhyloPhlAn and thanks for reporting this.

I tested and indeed I introduced a wrong flag when I updated the search for the local executables.
With commit 633d67242433131a369af27670ad698776853b1c I fixed this it now should work as expected.


Many thanks,
Francesco
