### ISSUE TITLE
How can I use my own database?

### ISSUE THREAD

**Issue by EdderDaniel** [biobakery/phylophlan#106]
I tried to use the  phylophlan_setup_database script to format my own set of core proteins that i have in a multifasta file which resulted in pretty much the same multifasta file with the name that i put on the -d option prefixed to each header, but when i tried to run the main pipeline i got the error message

`[e] database "genes/MY_OWN_DB.faa" not found in "phylophlan_databases/"
Available databases in "phylophlan_databases/":
    phylophlan_databases 
` 
aside from the error a directory called phylophlan_databases was also created with a txt file in it. Do i have to add my db to it manually? do i have to add it to the .cfg file that i used? Or did i do something wrong while running the phylophlan_setup_database script? I´m using the latest conda version of the program

Thanks!

**Comment by fasnicar** [comment]
Hi there, something might not have been executed the proper way, I think. Have you checked the [Database setup](https://github.com/biobakery/phylophlan/wiki#database-setup) section of the wiki?

Briefly, you need to put your multi-fasta inside a folder (let's say your multi-fasta is named `ecoli.fna`, so you can organize it in `ecoli/ecoli.fna`). Then you need to run `phylophlan_setup_database` and then you can specify in `phylophlan` the `-d ecoli` and `--databases_folder <PATH_TO_THE_ecoli_FOLDER>` (important, the path should not contain the `ecoli` folder, as that folder is what is considered as your database).

Let me know if something is not clear.

Many thanks,
Francesco

**Comment by EdderDaniel** [comment]
Thanks! It worked when i put the directory instead of the file!
