### ISSUE TITLE
Error in "Refining phylogeny"

### ISSUE THREAD

**Issue by catcatzilla** [biobakery/phylophlan#13]
Hi Francesco, 

I worked with Matthew. With your help, we successfully installed phylophlan3 on our cluster and complete the test run. 
However, when I used it on my real data, I got an error as shown below:
It seems the alignment and initial tree has been completed, but the error comes when there is a polytomies on the tree.

I am wondering if the initial tree is still accurate and useful. And how this can be fixed?

my command: 
phylophlan -i dereplicated_genomes_fna -d phylophlan -o dereplicated_genomes --nproc 16 --diversity high -f supermatrix_aa.cfg --verbose

Input are all fna genomes

The error is:

Concatenating alignments
Alignments concatenated "dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna_concatenated.aln" in 0s
Building phylogeny "dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna_concatenated.aln"
Phylogeny "dereplicated_genomes_fna.tre" built in 55s
Resolving 1 polytomies
Resolving polytomies for "dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna.tre"
"dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna_resolved.tre" generated in 0s

Refining phylogeny "dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna_resolved.tre"

[e] Command '['/tigress/MOLBIO/local/bin/raxmlHPC-PTHREADS-SSE3', '-p', '1989', '-m', 'PROTCATLG', '#threads#', '-t', 'dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna_resolved.tre', '-w', '/projects/DONIA/jliu/Temporal/Phylophlan3/dereplicated_genomes_fna_supermatrix_aa', '-s', 'dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna_concatenated.aln', '-n', 'dereplicated_genomes_fna_refined.tre']' returned non-zero exit status 127.

[e] error while executing
    command_line: /tigress/MOLBIO/local/bin/raxmlHPC-PTHREADS-SSE3 -p 1989 -m PROTCATLG #threads# -t dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna_resolved.tre -w /projects/DONIA/jliu/Temporal/Phylophlan3/dereplicated_genomes_fna_supermatrix_aa -s dereplicated_genomes_fna_supermatrix_aa/dereplicated_genomes_fna_concatenated.aln -n dereplicated_genomes_fna_refined.tre
           stdin: None
          stdout: None
             env: {'SLURM_NODELIST': 'tiger-h21d1', 'SLURM_JOB_NAME': 'runPhylophlan_dereplicated_genomes_fna-JL.sh', 'MANPATH': '/usr/share/man:/usr/local/share/man:/opt/puppetlabs/puppet/share/man', 'XDG_SESSION_ID': '55254', 'SLURMD_NODENAME': 'tiger-h21d1', 'SLURM_TOPOLOGY_ADDR': 'tiger-h21d1', 'HOSTNAME': 'tiger-h21d1', 'SELINUX_ROLE_REQUESTED': '', 'SLURM_NODE_ALIASES': '(null)', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'SLURM_JOB_QOS': 'tiger-donia', 'HISTSIZE': '1000', 'TMPDIR': '/tmp', 'SLURM_TOPOLOGY_ADDR_PATTERN': 'node', 'SSH_CLIENT': '128.112.70.123 52389 22', 'CONDA_SHLVL': '2', 'CONDA_PROMPT_MODIFIER': '(/tigress/MOLBIO/local/pythonenv/phylophlan)', 'SELINUX_USE_CURRENT_RANGE': '', 'NCARG_FONTCAPS': '/usr/lib64/ncarg/fontcaps', 'QTDIR': '/usr/lib64/qt-3.3', 'QTINC': '/usr/lib64/qt-3.3/include', 'SSH_TTY': '/dev/pts/261', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'SLURM_NNODES': '1', 'USER': 'jl103', 'LS_COLORS': 'rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:', 'CONDA_EXE': '/usr/licensed/anaconda3/2019.10/bin/conda', 'SLURM_JOBID': '4674298', 'COBBLER_SERVER': '10.36.16.2', 'SLURM_NTASKS': '16', 'NCARG_GRAPHCAPS': '/usr/lib64/ncarg/graphcaps', '_CE_CONDA': '.', 'CONDA_PREFIX_1': '/usr/licensed/anaconda3/2019.10', 'SLURM_TASKS_PER_NODE': '16', 'PATH': '/tigress/MOLBIO/local/diamond-0.9.31:/tigress/MOLBIO/local-rhel7/bin:/tigress/MOLBIO/local/pythonenv/phylophlan/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/jl103/.local/bin:/home/jl103/bin:/tigress/MOLBIO/local/bin', 'MAIL': '/var/spool/mail/jl103', 'SLURM_WORKING_CLUSTER': 'tiger2:tiger2-slurm:6820:8704:101', 'SLURM_JOB_ID': '4674298', 'CONDA_PREFIX': '/tigress/MOLBIO/local/pythonenv/phylophlan', 'SLURM_JOB_USER': 'jl103', 'PWD': '/tigress/DONIA/jliu/Temporal/Phylophlan3', '_LMFILES_': '/usr/licensed/Modules/modulefiles/anaconda3/2019.10:/tigress/MOLBIO/Modules/modulefiles-rhel7/blast/2.7.1:/tigress/MOLBIO/Modules/modulefiles-rhel7/diamond/0.9.31.132:/tigress/MOLBIO/Modules/modulefiles-rhel7/phylophlan/3.0', 'NCARG_ROOT': '/usr', 'LANG': 'en_US.UTF-8', 'MODULEPATH': '/tigress/MOLBIO/Modules/modulefiles-rhel7:/tigress/MOLBIO/Modules/modulefiles-shared:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/local/share/Modules/modulefiles:/opt/share/Modules/modulefiles:/usr/licensed/Modules/modulefiles:/projects/SOFTWARE/Modules/modulefiles/tiger', 'NCARG_DATABASE': '/usr/lib64/ncarg/database', 'SLURM_JOB_UID': '150058', 'LOADEDMODULES': 'anaconda3/2019.10:blast/2.7.1:diamond/0.9.31.132:phylophlan/3.0', 'SLURM_NODEID': '0', 'SLURM_SUBMIT_DIR': '/projects/DONIA/jliu/Temporal/Phylophlan3', 'SELINUX_LEVEL_REQUESTED': '', 'SLURM_TASK_PID': '41165', 'SLURM_NPROCS': '16', 'SLURM_CPUS_ON_NODE': '16', '_CE_M': '.', 'SLURM_PROCID': '0', 'ENVIRONMENT': 'BATCH', 'HISTCONTROL': 'ignoredups', 'NCARG_LIB': '/usr/lib64/ncarg', 'SLURM_JOB_NODELIST': 'tiger-h21d1', 'HOME': '/home/jl103', 'SHLVL': '2', 'NCARG_NCARG': '/usr/share/ncarg', 'SLURM_LOCALID': '0', 'SLURM_JOB_GID': '30054', 'SLURM_JOB_CPUS_PER_NODE': '16', 'SLURM_CLUSTER_NAME': 'tiger2', 'SLURM_GTIDS': '0', 'SLURM_SUBMIT_HOST': 'tigercpu.princeton.edu', 'SLURM_JOB_PARTITION': 'donia', 'CONDA_PYTHON_EXE': '/usr/licensed/anaconda3/2019.10/bin/python', 'LOGNAME': 'jl103', 'CVS_RSH': 'ssh', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'SLURM_JOB_ACCOUNT': 'molbio', 'SSH_CONNECTION': '128.112.70.123 52389 128.112.172.210 22', 'XDG_DATA_DIRS': '/home/jl103/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share', 'SLURM_JOB_NUM_NODES': '1', 'MODULESHOME': '/usr/share/Modules', 'CONDA_DEFAULT_ENV': '/tigress/MOLBIO/local/pythonenv/phylophlan', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'XDG_RUNTIME_DIR': '/run/user/150058', 'SLURM_MEM_PER_NODE': '153600', 'BASH_FUNC_module()': '() {  eval `/usr/bin/modulecmd bash $*`\n}', '_': '/tigress/MOLBIO/local/pythonenv/phylophlan/bin/phylophlan'}
Elapsed time is 116 minutes and 35 seconds.

Thank you! 
Jie

**Comment by fasnicar** [comment]
Dear Jie,
Thanks for reporting this. I believe the problem is in the configuration file as I see in the error message that the placeholder `#threads#` has not been replaced with the parameters and the number of threads to use (16, in your case).
Can I ask you to report the section `[tree2]` of the config file and the command line that generated that config file?

Apart from this, the non-refined tree you already have should be good enough to continue your analysis. Tree refinement step might not always be needed.


Many thanks,
Francesco

**Comment by catcatzilla** [comment]
Hi Francesco, 

The config file was generated using the phylophlan_write_default_configs.sh.
I saw the #threads# was not replaced. How should I replace this? Should it directly take the thread# from the command line?


[tree2]
program_name = /tigress/MOLBIO/local/bin/raxmlHPC-PTHREADS-SSE3
params = -p 1989 -m PROTCATLG
database = -t
input = -s
output_path = -w
output = -n
version = -v
command_line = #program_name# #params# #threads# #database# #output_path# #input# #output#

**Comment by fasnicar** [comment]
Hi 

Thanks for your reply.
This is strange because if I run (which is what is present in the `phylophlan_write_default_configs.sh` script):
```
phylophlan_write_config_file -o supermatrix_aa.cfg \
    -d a \
    --db_aa diamond \
    --map_dna diamond \
    --map_aa diamond \
    --msa mafft \
    --trim trimal \
    --tree1 fasttree \
    --tree2 raxml \
    --overwrite \
    --verbose
```


the `tree2` section looks like this:
```
[tree2]
program_name = /home/francesco/anaconda3/envs/ppa_test/bin/raxmlHPC-PTHREADS-SSE3
params = -p 1989 -m PROTCATLG
database = -t
input = -s
output_path = -w
output = -n
version = -v
command_line = #program_name# #params# #threads# #database# #output_path# #input# #output#
threads = -T
```

and correctly contains the definition for the `#threads#` placeholder (the order in which the definitions appear doesn't matter).

You can either try re-running the `phylophlan_write_default_configs.sh` script (or just the `phylophlan_write_config_file` command above) or you can simply manually add:
```
threads = -T
```

to the `tree2` section of your config file.

**Comment by catcatzilla** [comment]
Hi Francesco,

Thank you! I just re-running phylophlan_write_default_configs.sh. The threads = -T showed up. Thanks so much!

**Comment by catcatzilla** [comment]
Hi Francesco,

Even with the threads information (16 here), it still give an error message. 

[e] Command '['/tigress/MOLBIO/local/bin/raxmlHPC-PTHREADS-SSE3', '-p', '1989', '-m', 'PROTCATLG', '-T', '16', '-t', 'test/test_supermatrix_aa_output2/input_genomes_resolved.tre', '-w', '/projects/DONIA/jliu/Temporal/Phylophlan3/test/test_supermatrix_aa_output2', '-s', 'test/test_supermatrix_aa_output2/input_genomes_concatenated.aln', '-n', 'input_genomes_refined.tre']' returned non-zero exit status 127.

[e] error while executing
    command_line: /tigress/MOLBIO/local/bin/raxmlHPC-PTHREADS-SSE3 -p 1989 -m PROTCATLG -T 16 -t test/test_supermatrix_aa_output2/input_genomes_resolved.tre -w /projects/DONIA/jliu/Temporal/Phylophlan3/test/test_supermatrix_aa_output2 -s test/test_supermatrix_aa_output2/input_genomes_concatenated.aln -n input_genomes_refined.tre
           stdin: None
          stdout: None
             env: {'SLURM_NODELIST': 'tiger-h21d1', 'SLURM_JOB_NAME': 'testPhylophlan_supermatrix_aa.sh', 'MANPATH': '/usr/share/man:/usr/local/share/man:/opt/puppetlabs/puppet/share/man', 'XDG_SESSION_ID': '55878', 'SLURMD_NODENAME': 'tiger-h21d1', 'SLURM_TOPOLOGY_ADDR': 'tiger-h21d1', 'HOSTNAME': 'tiger-h21d1', 'SELINUX_ROLE_REQUESTED': '', 'SLURM_NODE_ALIASES': 

Best, 
Jie

**Comment by fasnicar** [comment]
Hi Jie,

Check whether you have files from the previous RAxML execution in the output directory. RAxML won't run if it finds files from a previous execution.
If that's not the case, you can run the RAxML command from the error message:
```/tigress/MOLBIO/local/bin/raxmlHPC-PTHREADS-SSE3 -p 1989 -m PROTCATLG -T 16 -t test/test_supermatrix_aa_output2/input_genomes_resolved.tre -w /projects/DONIA/jliu/Temporal/Phylophlan3/test/test_supermatrix_aa_output2 -s test/test_supermatrix_aa_output2/input_genomes_concatenated.aln -n input_genomes_refined.tre```

To better understand what RAxML doesn't like.

Thanks,
Francesco

**Comment by mcahn** [comment]
Hi Francesco,

An explanation of the missing "threads = -T": That happened because phylophlan_write_default_configs.sh output something that wasn't right for our environment.  The script seemed to think astral was here:
`
astral-4.11.1/astral.4.11.1.jar
`
whereas in our environment it's a newer version, and the full path needs to be specified.  So I edited the config files by hand and saved them.  After my most recent update of phylophlan, I put my copy of the config files back, but my copy didn't contain the "threads = -T" line.

So a new installation would be correct as far as the threads line goes, though I'm not sure why the astral path/version is wrong.

Best,
Matthew

**Comment by fasnicar** [comment]
Many thanks Matthew for the explanation!

The ASTRAL path is hardcoded into the `phylophlan_write_config_file.py` because there is no automatic way to find if ASTRAL is installed in a system or not as, as far as I understood, there is practically no installation for ASTRAL it just needs `java -jar astral.jar`.
It is briefly described here: https://github.com/biobakery/phylophlan/wiki#supertree-or-gene-trees
