### ISSUE TITLE
Can't locate phylophlan_write_default_configs.sh

### ISSUE THREAD

**Issue by swuyts** [biobakery/phylophlan#15]
Hi Francesco!

I just download Phylophlan 3 through Conda but can't seem to locate `phylophlan_write_default_configs.sh`. It is not exported in path. 

Could you check this out?

Many thanks,
Sander

**Comment by fasnicar** [comment]
Hi Sander,

I updated the PhyloPhlAn package in Bioconda that brings also other minor fixes from previous issues reported here.

You can update PhyloPhlAn and check if everything is working now.


Many thanks,
Francesco

**Comment by swuyts** [comment]
That work!

Thanks @fasnicar
