### ISSUE TITLE
Phylophlan_metagenomic 

### ISSUE THREAD

**Issue by kumar2501** [biobakery/phylophlan#16]
My output for a MAG shows Average distance of 0.35328 (from output_metagenomic.tsv) with its closest SGBs. What does it mean? How do we assign taxonomic label based on this value (Threshhold is <5%)? Can u please make it clear.
Thanks 
Jitesh

**Comment by fasnicar** [comment]
Dear Jitesh,

In your case, the average Mash distance of your MAG to the closest SGB is >30% so we would use the phylum label as a very high-level indication for further analysis to better characterize the MAG.
The thresholds we use to assign taxonomic labels are 5%, 15%, and 30% for SGB, GGB, and FGB, respectively, and were validated in the work: [Pasolli, E, et al. "Extensive unexplored human microbiome diversity revealed by over 150,000 genomes from metagenomes spanning age, geography, and lifestyle." _Cell_ (2019).](https://doi.org/10.1016/j.cell.2019.01.001).

One thing to consider though before doing any further analysis, is to check the completeness and contamination levels by running (for instance) CheckM on your MAG. This is to make sure that the average Mash distance is not an artifact of an incomplete and/or highly contaminated MAG. As for the thresholds, in the same work reported above, we considered medium-quality MAGs those with completeness >50% and contamination <5%, and high-quality MAGS those with completeness >90%, contamination <5%, and <0.5% polymorphic positions (computed using [CMSeq](https://github.com/SegataLab/cmseq)).


Best,
Francesco
