### ISSUE TITLE
--subsample None?

### ISSUE THREAD

**Issue by adityabandla** [biobakery/phylophlan#23]
The wiki says that the full alignment will be used if `--subsample` is set to `None`, however, it currently says that such an option doesn't exist

**Comment by fasnicar** [comment]
Hi,
To use the full alignment you simply don't need to specify the `--subsample` option and hence its value will be `None` and the full alignment will be used.

**Comment by adityabandla** [comment]
But `--subsample` seems to be enforced to some preset when using `--accurate` and `--diversity high`, is there a way to make it use the full alignment when using `--accurate` and `--diversity high`?

**Comment by fasnicar** [comment]
You're that you cannot select that option with the preset configurations present.
I'll fix this shortly and report here the commit ID that fixes this when done.
Many thanks,
Francesco

**Comment by fasnicar** [comment]
Hi, this is now fixed with commit ID 30117ce0e71a176d67f0c5d21f55f6a07fa89da8
The Bioconda package will not be updated shortly, so for the moment, please get PhyloPhlAn from the repository.

Many thanks,
Francesco
