### ISSUE TITLE
phylophlan_metagenomic, can not download database

### ISSUE THREAD

**Issue by PandengWang** [biobakery/phylophlan#24]
Thanks so much for releasing this extemely useful tool.
I'm in China.  For some reasons, people in China could not access google dropbox. 
It will throw a error as follow when I try to run phylophlan_metagenomic.

> [e] unable to download "https://www.dropbox.com/s/xdqm836d2w22npb/phylophlan_metagenomic.txt?dl=1"

It'll be great if you could provide another url link, such as FTP site, for Chinese user!
Thanks so much!

Best regard,
Pandeng

**Comment by fasnicar** [comment]
Dear Pandeng,

Thank you for using PhyloPhlAn, unfortunately, at the moment I don't have the database data available in a different place than Dropbox. 
I'll look if I can find an alternative place where to store the data.

Many thanks,
Francesco

**Comment by Yixiangzhang1996** [comment]
> Thanks so much for releasing this extemely useful tool.
> I'm in China. For some reasons, people in China could not access google dropbox.
> It will throw a error as follow when I try to run phylophlan_metagenomic.
> 
> > [e] unable to download "https://www.dropbox.com/s/xdqm836d2w22npb/phylophlan_metagenomic.txt?dl=1"
> 
> It'll be great if you could provide another url link, such as FTP site, for Chinese user!
> Thanks so much!
> 
> Best regard,
> Pandeng

The same

**Comment by wqssf** [comment]
> Thanks so much for releasing this extemely useful tool.
> I'm in China.  For some reasons, people in China could not access google dropbox.
> It will throw a error as follow when I try to run phylophlan_metagenomic.
> 
> [e] unable to download "https://www.dropbox.com/s/xdqm836d2w22npb/phylophlan_metagenomic.txt?dl=1"
> 
> It'll be great if you could provide another url link, such as FTP site, for Chinese user!
> Thanks so much!
> Best regard,
> Pandeng
您好，您的这个问题（需科学上网）：可以先根据报错里给出的那个链接去下载到一个txt文件，里面含有数据库信息，将数据库下载下来，解压，然后放在您在运行代码时指定的那个数据库路径下即可。我今天探索了一天，刚把环境配置好，对大佬的这个软件还不会灵活运用，希望能向您学习，我的邮箱：565715597@qq.com.

**Comment by PandengWang** [comment]
> > 您好，您的这个问题（需科学上网）：可以先根据报错里给出的那个链接去下载到一个txt文件，里面含有数据库信息，将数据库下载下来，解压，然后放在您在运行代码时指定的那个数据库路径下即可。我今天探索了一天，刚把环境配置好，对大佬的这个软件还不会灵活运用，希望能向您学习，我的邮箱：[565715597@qq.com](mailto:565715597@qq.com).

 @wqssf 谢谢提醒！这种方法我知道，也试过，但网速太不稳定，下载到12G的时候断掉，重新连接又要重新下，白白浪费了科学上网的流量。。。
你如果有下载好的数据库，不知能否共享一份给我，非常感谢！

**Comment by wqssf** [comment]
可以，可加QQ565715597,我通过网盘分享给您。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biobakery/phylophlan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月25日(星期六) 上午9:13
收件人:&nbsp;"biobakery/phylophlan"<phylophlan@noreply.github.com&gt;;
抄送:&nbsp;"Jonson"<565715597@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [biobakery/phylophlan] phylophlan_metagenomic, can not download database (#24)





   
您好，您的这个问题（需科学上网）：可以先根据报错里给出的那个链接去下载到一个txt文件，里面含有数据库信息，将数据库下载下来，解压，然后放在您在运行代码时指定的那个数据库路径下即可。我今天探索了一天，刚把环境配置好，对大佬的这个软件还不会灵活运用，希望能向您学习，我的邮箱：565715597@qq.com.
   
@wqssf 谢谢提醒！这种方法我知道，也试过，但网速太不稳定，下载到12G的时候断掉，重新连接又要重新下，白白浪费了科学上网的流量。。。
 你如果有下载好的数据库，不知能否共享一份给我，非常感谢！

**Comment by fasnicar** [comment]
Hi all, I just wanted to follow up on this. I now moved the databases to https://zenodo.org/ and I'm updating the Bioconda package to be able to download from the new location. I hope this should fix the Dropbox problem.

Many thanks,
Francesco

**Comment by wqssf102** [comment]
many thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "biobakery/phylophlan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 下午3:44
收件人:&nbsp;"biobakery/phylophlan"<phylophlan@noreply.github.com&gt;;
抄送:&nbsp;"Jonson"<565715597@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [biobakery/phylophlan] phylophlan_metagenomic, can not download database (#24)





 
Hi all, I just wanted to follow up on this. I now moved the databases to https://zenodo.org/ and I'm updating the Bioconda package to be able to download from the new location. I hope this should fix the Dropbox problem.
 
Many thanks,
 Francesco
