### ISSUE TITLE
Minimum quality for including MAGs?

### ISSUE THREAD

**Issue by adityabandla** [biobakery/phylophlan#28]
I am trying to build a de novo tree just using a set of MAG's we binned from a dataset. We have 295 of these at the species level with completeness > 50 % and redundancy < 10 %

We built the tree using `phylophlan -d phylophlan -f supermatrix_aa.cfg --diversity high --accurate`. But the tree seems quite sensitive to the way proteins are called, for example using only full proteins (prodigal with -c flag) or all proteins (including partial ones). Most clades seem stable, but some are quite variable.

When building de novo trees with just MAG's, without reference genomes, is there a threshold quality that is recommended?

**Comment by fasnicar** [comment]
Hi,

When working with MAGs you can specify some quality thresholds for (1) discarding MAGs that map less than a specified number of genes/proteins in the database using the `--min_num_markers` param and (2) discarding genes/proteins that mapped less than a specified number of MAGs using the `--min_num_entries` param.
Practically speaking, with (1) you're setting a quality threshold on your MAGs and with (2) you're deciding a coreness threshold on the genes/proteins in the database.
If you want to have as many MAGs as possible in your output phylogeny you probably don't want to be too stringent with (1), instead (2) can help you discard such genes/proteins that were mapped only for few MAGs and in the concatenated alignment will result in long gappy regions for all the other MAGs, and this can determine the fact that some clade are more stable than others,

Another thing I would suggest in your case is the use of `--force_nucleotides`. This will force the phylogenetic analysis to be based on nucleotides (regardless of the fact that the database are proteins) and this can be more stable/less sensitive for such MAGs that only partially map to a protein. Note that you should redo your configuration file specifying also for the `phylophlan_write_config_file` the `--force_nucleotides` param.

I hope this helps,
Francesco
