### ISSUE TITLE
local variable 'input_faa_clean' referenced before assignment

### ISSUE THREAD

**Issue by Y-H-Joe** [biobakery/phylophlan#31]
Dear phylophlan team,
    Thanks for your great effort in producing phylophlan 3.0.
    I recently occured same issue described in  #9 , however, I have successfully installed phylophlan from github, which should have no issue.
    So maybe something else is wrong.
    My error log:
`Traceback (most recent call last):
  File "/home/yzz0191/anaconda3/bin/phylophlan", line 11, in <module>
    load_entry_point('PhyloPhlAn==3.0', 'console_scripts', 'phylophlan')()
  File "/home/yzz0191/anaconda3/lib/python3.7/site-packages/PhyloPhlAn-3.0-py3.7.egg/phylophlan/phylophlan.py", line 3203, in phylophlan_main
    standard_phylogeny_reconstruction(project_name, configs, args, db_dna, db_aa)
  File "/home/yzz0191/anaconda3/lib/python3.7/site-packages/PhyloPhlAn-3.0-py3.7.egg/phylophlan/phylophlan.py", line 3008, in standard_phylogeny_reconstruction
    all_inputs = (os.path.splitext(os.path.basename(i))[0] for i in input_faa_clean)
UnboundLocalError: local variable 'input_faa_clean' referenced before assignment`

    It seems like error log in  #9 , but different, because the error line number in my case is 3203 and 3008, but 3200 and 3005 in #9 case. What's more, I have checked the "/home/yzz0191/anaconda3/lib/python3.7/site-packages/PhyloPhlAn-3.0-py3.7.egg/phylophlan/phylophlan.py", and I am pretty sure this python script is new version, the head of the script:

#!/usr/bin/env python

__author__ = ('Francesco Asnicar (f.asnicar@unitn.it), '
              'Francesco Beghini (francesco.beghini@unitn.it), '
              'Claudia Mengoni (claudia.mengoni@studenti.unitn.it), '
              'Mattia Bolzan (mattia.bolzan@unitn.it), '
              'Nicola Segata (nicola.segata@unitn.it)')
__version__ = '3.0.53'
__date__ = '8 June 2020'

    I really don't know how to fix it, and here is my code :
phylophlan  -i   ${input_folder}  -d phylophlan --force_nucleotides --diversity high     -f  supermatrix_aa.cfg --nproc 24

    Many thanks for any suggestions!

**Comment by fasnicar** [comment]
Hi,

Thanks for using PhyloPhlAn and for reporting this.
I believe your issue might be due to the content of your input folder. What's inside `${input_folder}`?


Many thanks,
Francesco

**Comment by Y-H-Joe** [comment]
Hi fasnicar, 
    Thanks for your reply. 
    In side the ${input_folder} is a single nucleotide file ( single-end WGS sequencing data ) named _cow.rn.seq400.fna_ .
    In my case, the name of the ${input_folder} is _ori_  , and here is the generated files in tree format:

phylophlan_cow_with_force/
├── [4.0K]  ori   ## the ${input_folder} here
│   └── [3.0G]  cow.rn.seq400.fna
├── [4.0K]  ori_phylophlan  ## generated by PhyloPhlAn
│   └── [4.0K]  tmp
│       ├── [4.0K]  map_dna
│       │   ├── [ 12G]  cow.rn.seq400.b6o.bkp
│       │   └── [5.1K]  cow.rn.seq400.b6o.bz2
│       ├── [4.0K]  markers
│       ├── [4.0K]  markers_dna
│       │   └── [175K]  cow.rn.seq400.fna.bz2
│       ├── [4.0K]  msas
│       ├── [4.0K]  sub
│       ├── [4.0K]  trim_gap_perc
│       ├── [4.0K]  trim_gap_trim
│       └── [4.0K]  trim_not_variant
└── [4.0K]  phylophlan_databases    ## generated by PhyloPhlAn
    ├── [4.0K]  phylophlan
    │   ├── [177M]  phylophlan.dmnd
    │   ├── [172M]  phylophlan.faa
    │   └── [ 64M]  phylophlan.faa.bz2
    ├── [ 305]  phylophlan_databases.txt
    ├── [  49]  phylophlan.md5
    └── [ 64M]  phylophlan.tar


    The process of PhyloPhlAn last  for several days before it crashed.

    here is the head of the input file cow.rn.seq400.fna:
>cow_000000000004
CTCCACGGACTTGACGGTGACAAAGTTCACGCCGTCCACCGACACCTGGATCTCGTAATC
CTCGGGGAAGACGTTGACCCCGTTCCACAGATCGCGGGGCACCAGCTTCACGCAGTTGAC
GTCGTACACCGCCAACAGGTCGATGGTGATCCACTCCTTGGAGGAGGCGCGCTCGTTGCG
GAACAGCTCGGAGGCCCAGGCCTTGGCGTAGTCGCCGTCGGTGATGTAGGTGTGGTGGCA
GGTCCATTCGGGCACGTCGGTGGTGGAGGAGTAGTCCACAACGGGCTTATGCAGGGCGAT
GTTCTCCCCCTCGGTCAGATCCGCCTCGGTGTAGGCGGTGGGGATCCTGTCGGGGATACT
GCCGTCGTCGTTGTAGACCATCATCTCACCGATATCCGCGTAGCCGCTGTTGCCCTTCAG
ACCGTTGACGCTGATGCGGA
>cow_000000000006
...
    
    the tail part is also same.
    Hope this helps.
    Thanks.

**Comment by fasnicar** [comment]
Thanks for these details.

I think the problem here is that you only have one input file, which if I understood correctly, is not a single genome (or MAG) but instead is a metagenome, right?
So, this does not make much sense, as (if possible) the output will be a tree with only one leaf (difficult to call it a tree).

I can add a check that the input folder should contain>4 files in order to avoid this in the future.

Thanks,
Francesco

**Comment by Y-H-Joe** [comment]
Thanks for reply.
    You're right, the input is a raw gut metagenome file (including many unknown microorganisms' reads). 
    So it seems that I misunderstood the usage of phylophlan, I have to assemble the raw reads into many bins, and put these bins into a folder, and finally feed the folder to phylophlan, right? I shouldn't just give a big file.
     Thanks.

**Comment by fasnicar** [comment]
Yes, sorry ti wasn't cleary from the tutorials.
The idea is that you can build a phylogenetic tree using both genomes, proteomes, and MAGs and additionally with `phylophlan_metagenomic` you can assign to your MAGs a taxonomy based on the SGBs (as defined here: https://www.sciencedirect.com/science/article/pii/S0092867419300017).
But there is no option at the moment with PhyloPhlAn that you can directly use raw reads.

Thanks,
Francesco

**Comment by Y-H-Joe** [comment]
Thanks fasnicar, it really helps!
