### ISSUE TITLE
Phylophan_metagenomic's mash dist uses all cpus despite using --nproc

### ISSUE THREAD

**Issue by jeanmanguy** [biobakery/phylophlan#35]
Hi,

Thank you for your work. 

Checking on our server with htop I realised that `mash dist` was using all of our CPUs. I believe it is caused by the missing `-p` argument here:

https://github.com/biobakery/phylophlan/blob/1b52049c7d61f0ff71e4209ae4cdd5ca2228cb4b/phylophlan/phylophlan_metagenomic.py#L513

While it is present in this call:

https://github.com/biobakery/phylophlan/blob/1b52049c7d61f0ff71e4209ae4cdd5ca2228cb4b/phylophlan/phylophlan_metagenomic.py#L554

**Comment by fasnicar** [comment]
Hi, many thanks for reporting this.
I explicitly added `'-p', '1'` to line 513 with commit 2378603a52e0b6e86cd87c47a848b3362bab32a9.
Can I ask you which version of mash you're running?
In the old versions, the default was `1` if not specified, but that might be changed in a new release.

Many thanks,
Francesco

**Comment by jeanmanguy** [comment]
Wonderful, thank you Francesco!

I am running phylophlan (3.0.31) and mash (2.2.2) out of bioconda. Yes I think I had the same issue when trying to use Mash for another project earlier this year, it feels like a familiar problem I had. At least we can use `-p`, that's weird though.
