### ISSUE TITLE
Is it possible to add eukaryotic core proteins to the PhyloPhlAn database?

### ISSUE THREAD

**Issue by charlottecc** [biobakery/phylophlan#37]
Hi all, 

I am new to this program and working with MAGs from skin microbiome samples. I need _Malassezia_ yeast to be included in my database. Is there a way to add species from this genera to the precomputed database? Or do I have to create a new one with both prokaryotic and eukaryotic information? 

I appreciate any help! Thanks!

**Comment by fasnicar** [comment]
Hi, the `phylophlan` database only contains marker genes for prokaryotes, so you cannot use it to study your _Malassezia_ MAGs. To study them you should first identify a set of core genes that are also single copy from your MAGs and then use those genes as a custom database in PhyloPhlAn.

I hope this helps,
Francesco
