### ISSUE TITLE
which tree should be used

### ISSUE THREAD

**Issue by fujch7** [biobakery/phylophlan#38]
Thank you for developing the amazing tool.

After I run it, which output file should I use? And why the raxml_bestree_final.tre didn't show branch value?

Thanks very much!

**Comment by fasnicar** [comment]
Hi, many thanks for using PhyloPhlAn.

The output phylogeny might depend on the configuration file you used. From your message I can understand you used RAxML to reconstruct the phylogenetic tree. So, in this case, the `RAxML_bestTree.*.tre` is the output file.
It is strange that there are no branch values though. can you provide the parameters you used in the configuration file for RAxML?

Many thanks,
Francesco

**Comment by fujch7** [comment]
run command：
nohup phylophlan -i /home/0811/ --accurate --diversity medium -d phylophlan -f supermatrix_aa.cfg -t a --nproc 2 --output_folder /home/phy_output &
configuration file is supermatrix_aa.cfg

The outputfile contains **raxml_besttree.0811_refine.tre**, **raxml_info.0811_refine.tre,** **raxml_log.0811_refine.tre**, **raxml_result.0811_refine.tre**, **0811.tre, 0811_resolved.tre**. 

**0811.tre** showed branch values but **raxml_besttree.0811_refine.tre didn't**.

Thanks very much!

**Comment by fasnicar** [comment]
Thanks, those are the defaults so it is strange that there are no branch lengths. Can you please send the ` raxml_besttree.0811_refine.tre` file?

**Comment by fujch7** [comment]
[RAxML_bestTree.0811_refined.zip](https://github.com/biobakery/phylophlan/files/5094991/RAxML_bestTree.0811_refined.zip)

**Comment by fasnicar** [comment]
Many thanks for the file. I correctly see the branch lengths in the file and it appears correctly visualized also from Archaeopteryx.

![Capture](https://user-images.githubusercontent.com/5664022/90620806-3cc4ae00-e213-11ea-9c16-42da94d7f7e7.PNG)

**Comment by fujch7** [comment]
- -! Sorry for misleading you. I mean the bootstrap value indicating the reliability of branches.

**Comment by fasnicar** [comment]
Ah! No problem.
The default config files do not perform the bootstrap analysis, you can add it by manually edit the configuration file and adding to the RAxML params the bootstrap parameters. Alternatively, you can run just RAxML with the bootstrap params using the MSA that you can find in the output folder.

**Comment by fujch7** [comment]
> 
> 
> Ah! No problem.
> The default config files do not perform the bootstrap analysis, you can add it by manually edit the configuration file and adding to the RAxML params the bootstrap parameters. Alternatively, you can run just RAxML with the bootstrap params using the MSA that you can find in the output folder.

Could I use concanated **concatenated.aln**file for just run  RAxML-ng？

**Comment by fasnicar** [comment]
Yes, of course. The `concatenated.aln` file is provided by PhyloPhlAn as output to be used for other downstream analyses, like testing/comparing a different/alternative phylogeny reconstruction tool.
