### ISSUE TITLE
Package folder not found

### ISSUE THREAD

**Issue by thh32** [biobakery/phylophlan#4]
I have just installed phylophlan3 using conda and am getting the following error straight away, any idea of the cause?

`(analysis) ecoli@bact:~/Hitch_analysis/analysis/v0.4/Output/Afrizal-2$ phylophlan -i Genome_tree -o Genome_tree/Output -d phylophlan --diversity medium
[e] "/home/ecoli/anaconda/envs/Analysis/lib/python3.8/site-packages/phylophlan/phylophlan_configs/" folder does not exists`

**Comment by fasnicar** [comment]
Hello Thomas,
which PhyloPhlAn package did you install?

As you can see from the [Biconda packages list](https://anaconda.org/bioconda/phylophlan/files) there are two packages for PhyloPhlAn:
```
noarch/phylophlan-3.0-py_1.tar.bz2
noarch/phylophlan-3.0-py_0.tar.bz2
```

And your problem might happen if you installed `phylophlan-3.0-py_0.tar.bz2`.

Many thanks,
Francesco

**Comment by thh32** [comment]
Thanks for the tip, that sorted out the problem. 

After having installed properly there was abit of a problem that the config files were not automatically present, or even the folder `phylophlan_configs`  but after creating the folder and running the `write_default_configs.sh` script it produced the files. 

Now I am facing another odd issue which may be related to the last one;
```
(phylo) ecoli@bact:~/Hitch_analysis/v0.4/Output/Afrizal-2$ phylophlan -i Genome_tree -o phylophlan_databases -d phylophlan -f supermatrix_aa.cfg --diversity medium --nproc 20
Loading files from "/DATA/Hitch_analysis/v0.4/Output/Afrizal-2/Genome_tree"
Loading files from "/DATA/Hitch_analysis/v0.4/Output/Afrizal-2/Genome_tree"
Inputs already checked
Inputs already cleaned
Loading files from "phylophlan_databases/tmp/clean_aa"
"phylophlan" markers already mapped (key: "map_aa")
Selecting 44 markers from "phylophlan_databases/tmp/map_aa"
Selecting "phylophlan_databases/tmp/map_aa/Agathobaculum_desmolans--GCF_000701665.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Ruthenibacterium_lactatiformans--GCF_000949455.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Flavonifractor_plautii--GCF_000239295.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Ruminococcus_albus--GCF_900109655.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Intestinimonas_butyriciproducens--GCA_003096335.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Acutalibacter_muris--GCF_002201475.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Ruminococcus_bromii--GCF_900101355.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Eubacterium_siraeum--GCF_000154325.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Ruminococcus_flavefaciens--GCF_000571935.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Clostridium_leptum--GCF_000154345.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Ruminococcus_champanellensis--GCF_000210095.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Acetanaerobacterium_elongatum--GCF_900103835.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Clostridium_sufflavum--GCF_003208175.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Gemmiger_formicilis--GCF_900167555.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Clostridium_cellobioparum--GCF_000621505.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Subdoligranulum_variabile--GCF_000157955.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Clostridium_cellulosi--GCF_000953215.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Clostridium_clariflavum--GCF_000237085.1_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Clostridium_papyrosolvens--GCF_000175795.2_genomic.b6o.bkp"
Selecting "phylophlan_databases/tmp/map_aa/Acetivibrio_cellulolyticus--GCF_000179595.2_genomic.b6o.bkp"

[e] expected str, bytes or os.PathLike object, not NoneType

[e] gene_markers_selection crashed
```

Thanks for any help you can provide.

**Comment by fasnicar** [comment]
Hello Thomas,

This I think it should not be related with the config file.
However, it is strange that when installing the new package you didn't find the `phylophlan_configs` folder and the 4 standard config file.

From the output you provided I see that you already run that analysis previously, so my guess is that there were some broken/empty files left in the folder from the previous run.
Can you remove the output folder `phylophlan_databases` and re-run PhyloPhlAn from scratch?


Many thanks,
Francesco

**Comment by thh32** [comment]
Hey Francesco,

You were totally write, there must have been some empty files leftover which caused the fault, it is now running fine!

Thanks for all the help,
Tom
