### ISSUE TITLE
Phylophlan_metagenomic.py

### ISSUE THREAD

**Issue by wangjianing0618** [biobakery/phylophlan#41]
Hi,
Thank you for this useful tool.

I got errors using phylophlan_metagenomic.py as follows:
phylophlan_metagenomic -i test -d SGB.Dec19 -o test-out --nproc 4 -n 10

The error details:
Traceback (most recent call last):
  File "/home/wjn/.conda/envs/phylophlan/bin/phylophlan_metagenomic", line 10, in <module>
    sys.exit(phylophlan_metagenomic())
  File "/home/wjn/.conda/envs/phylophlan/lib/python3.8/site-packages/phylophlan/phylophlan_metagenomic.py", line 884, in phylophlan_metagenomic
    f.write('\t'.join([binn] + ["{}_{}:{}:{}:{}".format(sgb_2_info[i[0]][5],
  File "/home/wjn/.conda/envs/phylophlan/lib/python3.8/site-packages/phylophlan/phylophlan_metagenomic.py", line 884, in <listcomp>
    f.write('\t'.join([binn] + ["{}_{}:{}:{}:{}".format(sgb_2_info[i[0]][5],
KeyError: '54917'

The attached file is the log.

Many thanks,
Jianing Wang

**Comment by wangjianing0618** [comment]
[test.log](https://github.com/biobakery/phylophlan/files/5130203/test.log)

**Comment by fasnicar** [comment]
Hi, many thanks for reporting this.
We had some problems with the Dec19 SGB release and it is now not among the ones available until the final version has been fixed.

Can you run:
```
phylophlan_metagenomic --database_update
``` 
This will update the available database and the latest is now `SGB.Nov19`.

Then, can you re-run your phylophlan_metagenomic using the `SGB.Nov19` database?
```
phylophlan_metagenomic -i test -d SGB.Dec19 -o test-out2 --nproc 4 -n 10 --verbose
```

Please, notice that I changed the output folder to `test-out2` to avoid that previous file can cause problems with the new run.


Many thanks,
Francesco

**Comment by wangjianing0618** [comment]
Thank you for your reply. Actually, I can't download and update the database directly because of unavailable network connection to google dropbox, I just copied the SGB.Dec19 from my partner. So, do you have any other ways to get the latest database now?

Best wishes,
Jianing Wang

**Comment by fasnicar** [comment]
Hi, I see. Unfortunately, I have the database available only through Dropbox at the moment.
These are the URLs of the 3 files needed for the latest db (`SGB.Nov19`):

- https://www.dropbox.com/s/68i0ddwoonhwzu1/SGB.Nov19.md5?dl=1
- https://www.dropbox.com/s/bvrz4zpt3538ct0/SGB.Nov19.tar?dl=1
- https://www.dropbox.com/s/zzo95dpfhq3n0h8/SGB.Nov19.txt.bz2?dl=1

Can you ask someone to download the for you if you can't download from Dropbox?

Thanks,
Francesco

**Comment by wangjianing0618** [comment]
I see, thank you very much for your help.

**Comment by fasnicar** [comment]
Hi Jianing Wang, I just wanted to follow up on this. I now moved the databases to https://zenodo.org/ and I'm updating the Bioconda package to be able to download from the new location. I hope this should fix the Dropbox problem.

Many thanks,
Francesco

**Comment by wangjianing0618** [comment]
This is really good news. Thank you very much for your understanding and support.

Best wishes,
Jianing Wang
