### ISSUE TITLE
occured core dumped

### ISSUE THREAD

**Issue by fujch7** [biobakery/phylophlan#45]
Hi Dr. Asnicar, 

    When I used multi threads to run phylophlan, it occured that error while mapping:

_[e] Command '['/root/anaconda3/envs/phylophlan/bin/diamond', 'blastp', '--quiet', '--threads', '1', '--outfmt', '6', '--more-sensitive', '--id', '50', '--max-hsps', '35', '-k', '0', '--query', '/mnt/hgfs/share/phylophlan3/output/0827faa_phylophlan/tmp/clean_aa/Ahniella_affigens_D13_T_GCA_003015185.1_prodigal_protein.faa', '--db', 'phylophlan_databases/phylophlan/phylophlan.dmnd', '--out', '/mnt/hgfs/share/phylophlan3/output/0827faa_phylophlan/tmp/map_aa/Ahniella_affigens_D13_T_GCA_003015185.1_prodigal_protein.b6o.bkp']' died with <Signals.SIGABRT: 6>.

[e] gene_markers_identification crashed_

And them I run `diamond blastp --threads 6 --outfmt 6 --more-sensitive --id 50 --max-hsps 35 -k 0 --query /mnt/hgfs/share/phylophlan3/0827faa/Dokdonella_koreensis_DS-123_T_GCA_001632775.1_prodigal_protein.faa --db phylophlan_databases/phylophlan/phylophlan.dmnd --out /mnt/hgfs/share/phylophlan3/output/0827faa_phylophlan/tmp/map_aa/Dokdonella_koreensis_DS-123_T_GCA_001632775.1_prodigal_protein.b6o.bkp`

It occured that **Aborted (core dumped)**:
_#CPU threads: 6
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /mnt/hgfs/share/phylophlan3/output/0827faa_phylophlan/tmp/map_aa
Opening the database...  [0.000605s]
#Target sequences to report alignments for: unlimited
Opening the input file...  [0.000501s]
Opening the output file...  [0.000501s]
Loading query sequences...  [0.005972s]
Masking queries...  [0.060089s]
Building query seed set...  [0.000322s]
Algorithm: Double-indexed
Building query histograms...  [0.03639s]
Allocating buffers...  [5.8e-05s]
Loading reference sequences...  [0.133974s]
Building reference histograms...  [4.28004s]
Allocating buffers...  [6.8e-05s]
Initializing temporary storage...  [0.057323s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [1.41807s]
Building query index...  [0.018558s]
Building seed filter...  [0.049821s]
Searching alignments... No such file or directory
Error: Error writing file /mnt/hgfs/share/phylophlan3/output/0827faa_phylophlan/tmp/map_aa/diamond-tmp-E9ek5S
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file /mnt/hgfs/share/phylophlan3/output/0827faa_phylophlan/tmp/map_aa/diamond-tmp-E9ek5S
Aborted (core dumped)_

It won't happened when I use single thread.

**Comment by fujch7** [comment]
I found this problem may be due to conda or other setup issues.
It works well after I deactivate conda and run diamond using multi threads. 
Perhaps I can install it using git, or use diamond under normal envs and move the output files to the path of **tmp** which used by phylophlan3, then activate phylophlan envs to run command phylophlan.
Hope this will work.

**Comment by fasnicar** [comment]
Hi and many thanks for reporting this.
Indeed, sometimes it might happen that external tools crash and, in general, for mafft and diamond it is likely due to temp files. There is a [Known issues](https://github.com/biobakery/phylophlan/wiki#known-issues) section in the PhyloPhlAn [wiki](https://github.com/biobakery/phylophlan/wiki) where we reported this.
I suggest you double-check write permission and space for the temp folder used by mafft, and in case you can specify an alternative location for temporary files by adding the `--tmpdir` param to the diamond parameters.
