### ISSUE TITLE
Location of examples folder and database files

### ISSUE THREAD

**Issue by KatariinaParnanen** [biobakery/phylophlan#48]
Hi! Installed phylophlan using conda. I am able to succesfully print the version after installation but my phylophlan directory does dot contain an examples folder. Am I supposed to clone the examples folder from github to be able to perform the tutorials?

Also, I would like to use the nucleotide version of the default databases for other purposes. Is this found somewhere in the phylophlan directories after installation or am I able to access it from somewhere else?

**Comment by fasnicar** [comment]
Hi, yes, the example folders are not packaged within the conda package, so you can get the files directly from the repository if you would like to test the tutorials.

About the databases, the default ones are only proteins and there are no nucleotides versions of them, but you can use the translated search (for instance diamond) to use them with both genomes and proteomes as inputs.
