### ISSUE TITLE
Any places could download the Built reference phylogeny 

### ISSUE THREAD

**Issue by 444thLiao** [biobakery/phylophlan#49]
Are any places we could download the reference phylogeny built in example2.

The software work fine. But if I want to use the tree directly because downloading and rebuilding are too computational expensive, is there any way to download it.

Thanks!

**Comment by fasnicar** [comment]
Hi, sorry I haven't provided the tree anywhere. Here https://www.dropbox.com/s/9lkxufl10cu6f3d/Figure4.nwk?dl=0 the Newick file of the phylogeny of Figure 4. The labels of the leaves are the SGB ID and you can find a match here to understand what they represent: https://opendata.lifebit.ai/table/sgb
