### ISSUE TITLE
verison

### ISSUE THREAD

**Issue by ganiatgithub** [biobakery/phylophlan#5]
Hey,

I have been using phylophlan2, thanks for the cool software, I installed it in a python 3 environment using:
`conda install -c bioconda phylophlan=3.0`

But when I check the version:
`phylophlan --version`
`PhyloPhlAn version 0.43 (2 March 2020)`

 I guess this is still v0.43 of phylophlan3?

Cheers

**Comment by fasnicar** [comment]
Hello Gani,

Yes, that's the "internal" version I'm using to keep track of changes. I should have probably updated to "3.0" in all scripts. Will do for the next release.

Thanks,
Francesco
