### ISSUE TITLE
The topology of the output trees 

### ISSUE THREAD

**Issue by MostafaYA** [biobakery/phylophlan#57]
Hi, 

I have used Phylophlan on a subset of genomes. The output included a number of tree files. I am wondering what are the differences between the files `*_resolved.tre` and `RAxML_bestTree.*_refined.tre`? and which one should be the final? as in my case, the topology of both trees was different. 

The topology of the `faa_resolved.tre` is similar to the core nucleotide analysis and also in agreement with the literature. 

I am using Phylophlan version 0.43 installed using conda. 

These are the two trees ... 

![Präsentation1](https://user-images.githubusercontent.com/25580655/111351936-f689dd00-8683-11eb-9eab-08c027915c0a.png)

Thank you very much for your help,

**Comment by fasnicar** [comment]
Hi, 

Please have a look at the **[Output](https://github.com/biobakery/phylophlan/wiki#output)** section of the wiki that explains exactly that.

Briefly, in your case, I believe your config file contains both the `[tree1]` and `[tree2]` sections, where `[tree1]` specifies to use FastTree for building an initial phylogeny and `[tree2]` specifies RAxML for refining the phylogeny reconstructed with FastTree. In this case, as also detailed in the [wiki](https://github.com/biobakery/phylophlan/wiki), the final tree is the `RAxML_bestTree.*.tre`.

About topology, consider that those trees are not rerooted w.r.t. anything, so you might need to reroot them before evaluating them properly.

The output folder contains both phylogenies and the MSA as those can be used for other downstream analyses.



Thanks,
Francesco

**Comment by MostafaYA** [comment]
Hi Francesco, thank you very much for your declaration.
