### ISSUE TITLE
phylophlan_strain_finder Error

### ISSUE THREAD

**Issue by LisaCarraro** [biobakery/phylophlan#62]
Hallo!
I would like to use "phylophlan_strain_finder" but these errors appear :

$ phylophlan_strain_finder -i RAxML_bestTree_refined.tre -m mutation_rates.tsv -o RESULT

Traceback (most recent call last):
  File "/opt/miniconda3/envs/phylophlan-2020.5/bin/phylophlan_strain_finder", line 10, in <module>
    sys.exit(phylophlan_strain_finder())
  File "/opt/miniconda3/envs/phylophlan-2020.5/lib/python3.8/site-packages/phylophlan/phylophlan_strain_finder.py", line 194, in phylophlan_strain_finder
    r = (check_thr(get_parent(tree, l), l, tree, mydict, args.phylo_thr, args.mutrate_thr, args.verbose))
  File "/opt/miniconda3/envs/phylophlan-2020.5/lib/python3.8/site-packages/phylophlan/phylophlan_strain_finder.py", line 159, in check_thr
    if any(md[(t[0], t[1])] > m_thr for t in tup):
  File "/opt/miniconda3/envs/phylophlan-2020.5/lib/python3.8/site-packages/phylophlan/phylophlan_strain_finder.py", line 159, in <genexpr>
    if any(md[(t[0], t[1])] > m_thr for t in tup):
KeyError: ('126', '128')

Thanks

Lisa

**Comment by fasnicar** [comment]
Hello Lisa, thanks for using PhyloPhlAn. Can I ask you the details about the command you used to generate the ` RAxML_bestTree_refined.tre` and the `mutation_rates.tsv` files?
Also, will you be able to share with me those two files, so that I can check them?

Many thanks,
Francesco

**Comment by LisaCarraro** [comment]
Dear Francesco,
thank you very much for the reply.

Detail of the command i used :

source activate phylophlan-2020.5

phylophlan_write_config_file \
    -o isolates_config.cfg \
    -d a \
    --force_nucleotides \
    --db_aa diamond \
    --map_aa diamond \
    --map_dna diamond \
    --msa mafft \
    --trim trimal \
    --tree1 fasttree \
    --tree2 raxml

phylophlan \
    -i fna \
    -o output_66 \
    -d database_lm \
    --diversity low \
    -t a \
    -f isolates_config.cfg \
    --force_nucleotides \
    --mutation_rates \
    --nproc 4 \
    --verbose 2>&1 | tee logs/phylophlan__output_isolates.log


phylophlan_strain_finder -i RAxML_bestTree_refined.tre -m
mutation_rates.tsv -o RESULT

In attach the files i used.

Thank you very much
Best

Lisa Carraro



Il giorno lun 17 mag 2021 alle ore 17:02 Francesco Asnicar <
***@***.***> ha scritto:

**Comment by fasnicar** [comment]
Many thanks Lisa, the commands look fine.
I apologize but I don't see any file attached either here or via email.
Can you please send them again? Will you also be able to send me the PhyloPhlAn log `phylophlan__output_isolates.log`?

Many thanks,
Francesco

**Comment by LisaCarraro** [comment]
Sorry, in attach the files.
[files_Lisa.zip](https://github.com/biobakery/phylophlan/files/6502680/files_Lisa.zip)

Thanks a lot
Lisa

**Comment by fasnicar** [comment]
Hi Lisa, many thanks for the files they were super-useful.

So, the problem was that pandas was interpreting the leaf IDs as numbers and the leaf IDs in the tree were strings. With this commit d9c2405f73e8229ce825e6b2bc7b27b42c831e0b I fixed it, many thanks for helping us improving and make PhyloPhlAn more stable.
My suggestion is for you to clone the latest version directly from the repository as we won't be able to update the package in Bioconda soon.

Many thanks,
Francesco

**Comment by LisaCarraro** [comment]
Thank you very much!
It works 👍
