### ISSUE TITLE
Generate the same tree

### ISSUE THREAD

**Issue by Biofarmer** [biobakery/phylophlan#71]
Hi, may I ask whether the exact same tree will be produced by phylophlan if running the exact setting for two times using the same version or any differences in trees produced by different versions? The version I used is version 3.0.60 and I also used version 3.0.58. The tree looks different from the two versions. 
Thanks
Wang

**Comment by fasnicar** [comment]
Hi Wang, thanks for using PhyloPhlAn, may I ask you how you're comparing the trees?

Version 3.0.58 and version 3.0.60 differ by the addition of some checks for the gene tree pipeline (804648deced5ede3d0a9286a20d93a9df5850a02) and the change of the download URL to an FTP server (295e8891626b8718fcf6c5967d3e5ee3c6b7dbbc). So, there are no changes about the phylogenetic analysis pipeline between those two versions.

It will be useful if you can also report the command line and the configuration you're using.

Many thanks,
Francesco

**Comment by Biofarmer** [comment]
Sent by email. Thanks
