### ISSUE TITLE
Need help for understanding how phylophlan works

### ISSUE THREAD

**Issue by RunJiaJi** [biobakery/phylophlan#75]
Hey guys, thank you for this excellent tool! I am new to the phylogenetic area and I do not quite understand how Phylophlan works.
Below is two questions that bother me and I'll be appreciated for some help.

**1.** I have tried phylophlan with a dataset containing 537 bacterial genomes. After the program finished, I found **400 markers' faa file** in the **genomes_phylophlan/tmp/markers** path, and different faa files contain different '>' (that is sequences). **My confusion is do these numbers mean that how many times phylophlan found the particular markers in my 537 bacterial genomes?**

![屏幕截图 2021-12-07 160329](https://user-images.githubusercontent.com/67813012/144990029-e8f270fe-f274-4d70-8161-c5adf2d3f717.jpg)

**2.** If different genomes contain different markers,  does it mean the **genomes_concatenated.aln** file is actually a small number (for example, 30) of markers sequences concatenated?

Hope I explained my thoughts clear. Thank you all!

**Comment by fasnicar** [comment]
Hi there!

So the `markers` folder contains the sequences of the specific marker (like `p0399`) that are found in your inputs (in the above case `p0399` is found in 256 inputs out of 537. It is quite normal that not all inputs contain all the markers and this also depend on the completeness of the input genomes (especially if you have MAGs).

The concatenated file instead contains the sequences of the markers found for the specific inputs, filled with gaps for those markers not found in the specific input. So, it is not a smaller set of sequences, simply it will be filled with gaps.

Of course, then it depends on the specific pipeline you're running, as you can discard inputs if they do not map enough markers (with the `phylophlan` database this is automatically set to 100, i.e. 25%). You can also discard markers to be considered in the concatenation if they do not map enough inputs. Then the actual amount of gaps that will be introduced for those markers that are not mapped will depend on the subsample param as in the case of the `phylophlan` database there is a formula saying how many positions for each of the 400 markers should be considered.

I hope this clarifies a bit what is happening. Also, the [wiki](https://github.com/biobakery/phylophlan/wiki) could be a good place to look for how these params work and can be tuned in the specific analysis.

Many thanks,
Francesco

**Comment by RunJiaJi** [comment]
Hi, Francesco. Thank you so much for your detailed explanation！I will go through the wiki page!
Wish you a nice day!
