### ISSUE TITLE
no inputs found, please check your params and inputs file extensions error

### ISSUE THREAD

**Issue by nishu92** [biobakery/phylophlan#78]
Hii Sir,
I have installed the PhyloPhlan 3.0, and I am trying to construct the **Tree of life** with this. I am doing everything told (https://github.com/biobakery/biobakery/wiki/PhyloPhlAn-3.0%3A-Example-02%3A-Tree-of-life) but every time running the command, I am getting the error as following "no inputs found, please check your params and inputs file extensions". However, the extensions of downloaded reference genomes and my assembled MAGs are .fna files. 
Pl. help

Best regards

**Comment by nishu92** [comment]
This is script I am using to submit the job 
phylophlan -i /home/nitishs/anaconda3/envs/phylophlan/[output_folder]/TOL/input_genomes -d phylophlan -f /home/nitishs/anaconda3/envs/phylophlan/[output_folder]/TOL/02_tol.cfg --diversity high --fast -o output_tol --nproc 190 --verbose

**Comment by fasnicar** [comment]
Hi, can you please provide the version of PhyloPhlAn you're using (command: `phylophlan --version`) and the full output (you can redirect what PhyloPhlAn prints by adding `2>&1 | tee phylophlan.log` to your command above, but before re-running PhyloPhlAn, please remove the output folder so you'll do a clean run)?

Many thanks,
Francesco

**Comment by nishu92** [comment]
Hi sir, 
Thank you for your response. 
Sorry for the late reply; actually, I had everything deleted mistakenly. 

I am using PhyloPhlAn version 3.0.60 (27 November 2020). Pl. find attached the PhyloPhlAn log file. 
[phylophlan.log](https://github.com/biobakery/phylophlan/files/7859949/phylophlan.log)

Thanks & regards
Nitish

**Comment by fasnicar** [comment]
Dear Nitish, thank you for sending the log file.
Can you please send the output of `ls /home/nitishs/anaconda3/envs/phylophlan/[output_folder]/TOL/input_genomes`?
Thank you!

**Comment by nishu92** [comment]
Thank you for your reply, sir, 
I re-run the entire script from a new directory other than [ output folder ], and fortunately, it worked. I am heartily thankful for your quick assistance and this beautiful tool. 

Thanks and regards
Nitish

**Comment by wanboqi** [comment]
Hii Sir, 
       I have the same problem.I don't understand why I can't detect the input data. I'm sure the path is correct. Could you please ask me how to solve it? My command is phylophlan -i /home/wbq/test/data/08_dRep/dRep/dRep99/dereplicated_genomes -d /home/public/database/Phylophlan/phylophlan_databases/phylophlan --diversity high --accurate -o output --nproc 8 -f /home/public/miniforge3/envs/phylophlan/lib/python3.11/site-packages/phylophlan/phylophlan_configs/supertree_aa.cfg --verbose

**Comment by fasnicar** [comment]
Hi @wanboqi, can you please check the extension of your inputs?
PhyloPhlAn uses as defaults `.fna` for genomes and `.faa` for proteomes. These can be tuned with the `--genome_extension` and `--proteome_extension` parameters.

Many thanks,
Francesco

**Comment by wanboqi** [comment]
@fasnicar Thank you for your guidance, after adding the parameter -- genome_extension .fa, it can run normally.
