### ISSUE TITLE
Diamond error

### ISSUE THREAD

**Issue by LisaCarraro** [biobakery/phylophlan#79]
Hi,

I have tried several times but I cannot use the genome that I am attaching. 

I get this error message:

[e] Command '['/opt/miniconda3/envs/phylophlan-2020.5/bin/diamond', 'blastx', '--quiet', '--threads', '1', '--outfmt', '6', '--more-sensitive', '--id', '50', '--max-hsps', '35', '-k', '0', '--query', '/home/lcarraro/listerie/prova_01_2022/330.fna', '--db', '/home/lcarraro/listerie/database_lm/database_lm.dmnd', '--out', 'output/tmp/map_dna/330.b6o.bkp']' returned non-zero exit status 1.

with  many other my genomes it works, if I add genome "330" it doesn't work.
[330.docx](https://github.com/biobakery/phylophlan/files/7857466/330.docx)

 Is it a quality problem of my genome?

Thanks 
Lisa

**Comment by fasnicar** [comment]
Dear Lisa, thank you for reporting this.
Have you try runnning the diamond command for that genome to see if there is a specific error from diamond?
```
/opt/miniconda3/envs/phylophlan-2020.5/bin/diamond blastx --threads 1 --outfmt 6 --more-sensitive --id 50 --max-hsps 35 -k 0 --query /home/lcarraro/listerie/prova_01_2022/330.fna --db /home/lcarraro/listerie/database_lm/database_lm.dmnd --out output/tmp/map_dna/330.b6o.bkp
```

Also, it might be helpful (if you have it) to send the log file from PhyloPhlAn.

Many thanks,
Francesco

**Comment by LisaCarraro** [comment]
Thank you very much!

(phylophlan-2020.5) [lcarraro@p04-64gb /]$ /opt/miniconda3/envs/phylophlan-2020.5/bin/diamond blastx --threads 1 --outfmt 6 --more-sensitive --id 50 --max-hsps 35 -k 0 --query  /home/lcarraro/listerie/prova_01_2022/330.fna --db /home/lcarraro/listerie/database_lm/database_lm.dmnd --out /home/lcarraro/listerie/output/map_dna/330_p.b6o.bkp


diamond v0.9.32.133 (C) 

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /home/lcarraro/listerie/output/map_dna
Opening the database...  [0s]
#Target sequences to report alignments for: unlimited
Reference = /home/lcarraro/listerie/database_lm/database_lm.dmnd
Sequences = 9395
Letters = 2906376
Block size = 2000000000
Opening the input file...  [0s]
Opening the output file...  [0s]
Loading query sequences...  [0.029s]
Error: Error reading input stream at line 32586: Invalid character (ASCII 9) in sequence


Thanks!
Lisa

**Comment by fasnicar** [comment]
Thank you! So, ASCII 9 is the TAB character, and if you search for it you'll find that at line 32586 (same line as in the error message from diamond) you have a sequence ending with a TAB character (see screenshot below):
![image](https://user-images.githubusercontent.com/5664022/149375786-e09547fe-5f86-4399-9cb2-a12850fbb1a7.png)
I think that if you correct that then you should be able to run this genome through PhyloPhlAn then!

Many thanks,
Francesco

**Comment by LisaCarraro** [comment]
Thank you very much for your help!!
Your support is always really precious.

Best
Lisa


Il gio 13 gen 2022, 18:06 Francesco Asnicar ***@***.***> ha
scritto:

**Comment by YR020202** [comment]
Hello,
I also encountered the above problems, but when I ran the diamond command, I encountered the following errors:

$/home/shpc_101903/miniconda3/envs/phylophlan/bin/diamond blastx --threads 1 --outfmt 6 --more-sensitive --id 50 --max-hsps 35 -k 0 --query /home/shpc_101903/data2/MAG_tree/nitrificans.fna --db /home/shpc_101903/miniconda3/envs/phylophlan/phylophlan_databases/phylophlan/phylophlan.dmnd --out /home/shpc_101903/data2/output/nitrificans.b6o.bkp

Error: Out_of_range query= target=DSIGHGTKASVPVVPVFNMKGFATRVDRKKKAILSTSGELLDWKNLLFIVGLNRKSIQSVIKKDQESFGDRADVIYLVIDVANLISIARIVSYYEISEYVKQRKRIGATDAIIFKYQKFEVHGTVVDRTTGARDCVLSVTRRMLYNMLTSKGTNPKGVIALRVVDDKPLERREDVSFLNQIIARELADINRGHEASVCILTSFGYRAYNYHVEEGGETKNVAAILKGWYPRLYQIVEEDEASECTGDLVLLIKDACQISKYTQELVLTDIHQRSAKKESFVTF________________________________________________________PLVKYSFHRGGDCLIVDQGKM

**Comment by YR020202** [comment]
Hello,
I also encountered the above problems, but when I ran the diamond command, I encountered the following errors:

$/home/shpc_101903/miniconda3/envs/phylophlan/bin/diamond blastx --threads 1 --outfmt 6 --more-sensitive --id 50 --max-hsps 35 -k 0 --query /home/shpc_101903/data2/MAG_tree/MAG_237.fna --db /home/shpc_101903/miniconda3/envs/phylophlan/phylophlan_databases/phylophlan/phylophlan.dmnd --out /home/shpc_101903/data2/output/MAG_237.b6o.bkp

Error: Out_of_range query= target=DSIGHGTKASVPVVPVFNMKGFATRVDRKKKAILSTSGELLDWKNLLFIVGLNRKSIQSVIKKDQESFGDRADVIYLVIDVANLISIARIVSYYEISEYVKQRKRIGATDAIIFKYQKFEVHGTVVDRTTGARDCVLSVTRRMLYNMLTSKGTNPKGVIALRVVDDKPLERREDVSFLNQIIARELADINRGHEASVCILTSFGYRAYNYHVEEGGETKNVAAILKGWYPRLYQIVEEDEASECTGDLVLLIKDACQISKYTQELVLTDIHQRSAKKESFVTF________________________________________________________PLVKYSFHRGGDCLIVDQGKM

This is the genome “MAG_237”
Thanks!
[MAG_237.txt](https://github.com/biobakery/phylophlan/files/11428502/MAG_237.txt)

WYR
