### ISSUE TITLE
Does Phylophlan  support genome multiple alignment of samples as multiple contigs? 

### ISSUE THREAD

**Issue by ne1al** [biobakery/phylophlan#86]
Hi,
I have samples assembled to multiple contigs. I would like to construct a phylogenomic tree based on contigs of the samples. Does Phylophlan support this?
Thank You

**Comment by fasnicar** [comment]
Hi, 
You can use contigs data within PhyloPhlAn, although contigs should be first clustered into bins.
I hope this helps.

Thank you,
Francesco

**Comment by ne1al** [comment]
@fasnicar does it need a special software for binning?
