### ISSUE TITLE
[Enhancement] Future plans for fungi

### ISSUE THREAD

**Issue by llk578496** [biobakery/phylophlan#94]
Hi @fbeghini ,

We are working on the core-genome on fungi now. And we are really struggling in how to create a core-genome phylogeny for fungi.

May I ask it is possible for phylophlan also include fungi (e.g. Candida auris) in the analysis?

Thank you very much.

**Comment by fasnicar** [comment]
Hi @llk578496, can I ask you what you mean by your question:

> May I ask it is possible for phylophlan also include fungi (e.g. Candida auris) in the analysis?

If you have identified a set of marker genes that you think you can use in your phylogenetic analysis, you can use those as a database of markers and build your fungi-specific phylogeny. I might not get your point, or is this what you would like to do?


Many thanks,
Francesco

**Comment by llk578496** [comment]
Hi @fasnicar ,
Yes! That's exactly what I would like to do!
Thank you very much!
